version: "2.1"
services:
  fxa-oauth-console:
    build:
      context: .
      dockerfile: Dockerfile-build
    command: node bin/server.js
    image: mozilla/fxa-oauth-console
    ports:
      - "10137:10137"
    environment:
      PROFILE_URI: https://latest.dev.lcip.org/profile/v1
      OAUTH_INTERNAL_URI: https://127.0.0.1:9011/v1
      PROFILE_URI: https://127.0.0.1:1111/profile/v1
